-- Digital Art NFT Marketplace & Creator Economy - Oracle Object-Relational Database
-- Fixed Drop Script - Proper cleanup order to handle dependencies

-- Drop Triggers
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_nft_creation';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_sale_transaction';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_creator_registration';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_auction_bid';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Views
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW nft_marketplace_view';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW creator_analytics_view';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Procedures
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE create_nft';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE process_sale';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Functions
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION get_creator_earnings';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION calculate_platform_fees';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION get_collection_stats';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Indexes
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_nft_creator';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_nft_collection';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_nft_price';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_nft_created_at';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX idx_transaction_timestamp';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Tables (in dependency order)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE nft CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transaction_history CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE auction CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE creator CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE nft_collection CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE marketplace CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Sequences
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE creator_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE nft_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE transaction_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE collection_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE auction_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE marketplace_id_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Nested Table Types
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE transaction_table_type';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE bid_table_type';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Subtypes First (in reverse inheritance order)
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE premium_creator_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE verified_creator_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Drop Base Types
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE creator_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE transaction_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE auction_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE collection_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE marketplace_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE bid_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE tag_array_type FORCE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

COMMIT;